// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtGlNDy5ah_R_fu3iwJ3PJID1NuCaMgK8',
    appId: '1:326363186525:web:dacd9a8bcbc64942a094b4',
    messagingSenderId: '326363186525',
    projectId: 'delivery--app-ffcc9',
    authDomain: 'delivery--app-ffcc9.firebaseapp.com',
    storageBucket: 'delivery--app-ffcc9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRgPLZ9cBM6Hcvv9gWLSdE7mO3ClTvmp8',
    appId: '1:326363186525:android:0b397a04f501b291a094b4',
    messagingSenderId: '326363186525',
    projectId: 'delivery--app-ffcc9',
    storageBucket: 'delivery--app-ffcc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4XyQn0_s4_MsodQfjTShF4EEIYUG3tBc',
    appId: '1:326363186525:ios:a41e69e091a07f10a094b4',
    messagingSenderId: '326363186525',
    projectId: 'delivery--app-ffcc9',
    storageBucket: 'delivery--app-ffcc9.appspot.com',
    androidClientId: '326363186525-2n0uburoqrombcbr9rc2junk9ldfuc2v.apps.googleusercontent.com',
    iosClientId: '326363186525-566hgvulv3d08ipnqe9c8e1dledpmso2.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliverlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4XyQn0_s4_MsodQfjTShF4EEIYUG3tBc',
    appId: '1:326363186525:ios:a41e69e091a07f10a094b4',
    messagingSenderId: '326363186525',
    projectId: 'delivery--app-ffcc9',
    storageBucket: 'delivery--app-ffcc9.appspot.com',
    androidClientId: '326363186525-2n0uburoqrombcbr9rc2junk9ldfuc2v.apps.googleusercontent.com',
    iosClientId: '326363186525-566hgvulv3d08ipnqe9c8e1dledpmso2.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliverlyApp',
  );
}
